linters:
  enable:
    - depguard
    - unconvert
    - gofmt
    - goimports
    - misspell

linters-settings:
  depguard:
    list-type: denylist
    include-go-root: true
    packages:
      # use "io" or "os" instead
      # https://go.dev/doc/go1.16#ioutil
      - io/ioutil
