version: "2"
linters:
  enable:
    - depguard
    - misspell
    - revive
    - unconvert
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
          deny:
            - pkg: io/ioutil
    revive:
      severity: error
      rules:
        - name: indent-error-flow
          severity: warning
          disabled: false
        - name: error-strings
          disabled: false
    staticcheck:
      checks:
        - -SA1019
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
