dist: bionic
language: go

os:
- linux

go:
  - "1.16.x"
  - "1.18.x"

matrix:
  include:
    - os: linux

addons:
  apt:
    packages:
    - gnutls-bin
    - softhsm2

go_import_path: github.com/containers/ocicrypt

install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1

script:
  - make
  - make check
  - make test
