name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19', '1.18' ]
    name: Go Version ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: sudo apt-get install -y gnutls-bin softhsm2

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Install
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1

    - name: Build
      run: make

    - name: Run golangci-lint
      run: make check

    - name: Test
      run: make test
